variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_server" {}
variable "vsphere_dc_name" {}
variable "vsphere_dscluster" {}
variable "vsphere_compute_cluster" {}
variable "vsphere_portgroup_name" {}
variable "vsphere_folder" {}
variable "vsphere_template_name" {}
variable "winadmin_password" {}
variable "PDC_name" {}
variable "ReplicaDC_name" {}
variable "Fileserver_name" {}
variable "PDC_IP" {}
variable "ReplicaDC_IP" {}
variable "Fileserver_IP" {}
variable "netmask" {}
variable "def_gw" {}
variable "dns_server" {}
variable "PDC_cpu_num" {}
variable "ReplicaDC_cpu_num" {}
variable "Fileserver_cpu_num" {}
variable "PDC_mem" {}
variable "ReplicaDC_mem" {}
variable "Fileserver_mem" {} 